ALTER TABLE vs_e_order
    ADD COLUMN INN_DEALER VARCHAR(20) NULL DEFAULT NULL COMMENT 'ИНН дилера' AFTER DEALER_USER_ID,
    ADD COLUMN SALON_CODE VARCHAR(50) NULL DEFAULT NULL COMMENT 'Код салона' AFTER INN_DEALER,
    ADD INDEX ix_inn_dealer (INN_DEALER),
    ADD INDEX ix_salon_code (SALON_CODE);