### Login by ligron user
POST https://ligron/login/
Content-Type: application/json

{
  "customMode": "remoteDB",
  "cmsAction": "login",
  "loginType": "manager",
  "login": "ladmin1",
  "password": "pass1"
}

### Login by dealer user
POST https://ligron/login/
Content-Type: application/json

{
  "customMode": "remoteDB",
  "cmsAction": "login",
  "loginType": "dealer",
  "login": "dealer_user1",
  "password": "hash1"
}

### Login by dealer user - wrong auth
POST https://ligron/login/
Content-Type: application/json

{
  "customMode": "remoteDB",
  "cmsAction": "login",
  "loginType": "dealer",
  "login": "dealer_user1",
  "password": "hashWrong"
}
